modLoader = "javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL = "https://github.com/Oiha-dev/minemath/issues"
license = "Creative Commons BY-NC-SA 4.0"

[[mods]]
modId = "minemath"
version="${mod_version}"
displayName = "MineMath"
authors = "Oiha"
displayURL = "https://oiha.fr"
logoBlur = false
description = '''
MineMath - Your Mathematical GUI Calculator Companion in Minecraft
'''
logoFile = "assets/minemath/icon.png"

[[dependencies.minemath]]
modId = "forge"
mandatory = true
versionRange="${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.minemath]]
modId = "minecraft"
mandatory = true
versionRange="${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

