modLoader = "javafml"
loaderVersion = "[9,)"
issueTrackerURL = "https://github.com/Oiha-dev/minemath/issues"
license = "Creative Commons BY-NC-SA 4.0"

[[mods]]
modId = "minemath"
version = "3.0.0"
displayName = "MineMath"
authors = "Oiha"
displayURL = "https://oiha.fr"
logoBlur = false
description = '''
MineMath - Your Mathematical GUI Calculator Companion in Minecraft
'''
logoFile = "assets/minemath/icon.png"

[[dependencies.minemath]]
modId = "neoforge"
type = "required"
versionRange = "[21.7,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.minemath]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.7,)"
ordering = "NONE"
side = "BOTH"

